// export const STATIC_MCPS = [
//   // Developer Tools
//   {
//     name: "GitHub (Enterprise)",
//     description:
//       "Connect to GitHub Enterprise instances. Manage repos and issues.",
//     command: "npx",
//     args: ["-y", "@modelcontextprotocol/server-github"],
//     env: {
//       GITHUB_API_URL: "https://github.example.com/api/v3",
//       GITHUB_TOKEN: "your-token",
//     },
//     tags: ["developer", "git", "enterprise"],
//     icon: { type: "emoji", value: "🏢" },
//   },
//   {
//     name: "GitLab",
//     description:
//       "Interact with GitLab repositories, pipelines, and merge requests.",
//     command: "npx",
//     args: ["-y", "@modelcontextprotocol/server-gitlab"],
//     env: { GITLAB_TOKEN: "your-token" },
//     tags: ["developer", "git", "gitlab"],
//     icon: { type: "emoji", value: "🦊" },
//   },
//   {
//     name: "Kubernetes",
//     description: "Manage K8s clusters, pods, and deployments directly.",
//     command: "npx",
//     args: ["-y", "@modelcontextprotocol/server-kubernetes"],
//     tags: ["developer", "devops", "k8s"],
//     icon: { type: "emoji", value: "☸️" },
//   },
//   {
//     name: "AWS CLI",
//     description: "Wrapper around AWS CLI for managing cloud resources.",
//     command: "npx",
//     args: ["-y", "@modelcontextprotocol/server-aws"],
//     tags: ["developer", "cloud", "aws"],
//     icon: { type: "emoji", value: "☁️" },
//   },
//   {
//     name: "Linear",
//     description: "Manage issues and projects in Linear.",
//     command: "npx",
//     args: ["-y", "@modelcontextprotocol/server-linear"],
//     env: { LINEAR_API_KEY: "your-key" },
//     tags: ["developer", "project-management", "linear"],
//     icon: { type: "emoji", value: "🔷" },
//   },
//   {
//     name: "Jira",
//     description: "Create and update Jira tickets and sprints.",
//     command: "npx",
//     args: ["-y", "@modelcontextprotocol/server-jira"],
//     env: { JIRA_API_TOKEN: "your-token", JIRA_DOMAIN: "your-domain" },
//     tags: ["developer", "project-management", "jira"],
//     icon: { type: "emoji", value: "📋" },
//   },
//   {
//     name: "Notion",
//     description: "Read and write to Notion pages and databases.",
//     command: "npx",
//     args: ["-y", "@modelcontextprotocol/server-notion"],
//     env: { NOTION_API_KEY: "your-key" },
//     tags: ["productivity", "docs", "notion"],
//     icon: { type: "emoji", value: "📓" },
//   },
//   {
//     name: "Terminal",
//     description: "Execute shell commands (sandboxed).",
//     command: "npx",
//     args: ["-y", "@modelcontextprotocol/server-terminal"],
//     tags: ["developer", "system", "terminal"],
//     icon: { type: "emoji", value: "💻" },
//   },
//
//   // Databases & Storage
//   {
//     name: "MySQL",
//     description: "Connect to MySQL databases.",
//     command: "npx",
//     args: [
//       "-y",
//       "@modelcontextprotocol/server-mysql",
//       "mysql://user:pass@host/db",
//     ],
//     tags: ["database", "sql"],
//     icon: { type: "emoji", value: "🐬" },
//   },
//   {
//     name: "MongoDB",
//     description: "Query and aggregate data in MongoDB.",
//     command: "npx",
//     args: [
//       "-y",
//       "@modelcontextprotocol/server-mongodb",
//       "mongodb://localhost:27017",
//     ],
//     tags: ["database", "nosql", "mongo"],
//     icon: { type: "emoji", value: "🍃" },
//   },
//   {
//     name: "Redis",
//     description: "Manage Redis keys and cache.",
//     command: "npx",
//     args: [
//       "-y",
//       "@modelcontextprotocol/server-redis",
//       "redis://localhost:6379",
//     ],
//     tags: ["database", "cache", "redis"],
//     icon: { type: "emoji", value: "🔺" },
//   },
//   {
//     name: "Google Drive",
//     description: "Access files and folders in Google Drive.",
//     command: "npx",
//     args: ["-y", "@modelcontextprotocol/server-gdrive"],
//     tags: ["storage", "google", "cloud"],
//     icon: { type: "emoji", value: "📁" },
//   },
//   {
//     name: "Dropbox",
//     description: "Manage files in Dropbox.",
//     command: "npx",
//     args: ["-y", "@modelcontextprotocol/server-dropbox"],
//     tags: ["storage", "cloud"],
//     icon: { type: "emoji", value: "📦" },
//   },
//   {
//     name: "S3 Bucket",
//     description: "Upload and download from AWS S3.",
//     command: "npx",
//     args: ["-y", "@modelcontextprotocol/server-s3"],
//     tags: ["storage", "aws", "cloud"],
//     icon: { type: "emoji", value: "🪣" },
//   },
//
//   // Communication
//   {
//     name: "Discord",
//     description: "Send messages and manage Discord channels.",
//     command: "npx",
//     args: ["-y", "@modelcontextprotocol/server-discord"],
//     env: { DISCORD_TOKEN: "your-token" },
//     tags: ["communication", "chat", "discord"],
//     icon: { type: "emoji", value: "🎮" },
//   },
//   {
//     name: "Gmail",
//     description: "Read and send emails via Gmail API.",
//     command: "npx",
//     args: ["-y", "@modelcontextprotocol/server-gmail"],
//     tags: ["communication", "email", "google"],
//     icon: { type: "emoji", value: "📧" },
//   },
//   {
//     name: "Google Calendar",
//     description: "Manage calendar events.",
//     command: "npx",
//     args: ["-y", "@modelcontextprotocol/server-gcal"],
//     tags: ["productivity", "calendar", "google"],
//     icon: { type: "emoji", value: "📅" },
//   },
// ];

export const STATIC_MCPS: any[] = [];
